### ISSUE TITLE
Where is the commander?

### ISSUE THREAD

**Issue by nicolasmaia** [vss-devel/zimmer#11]
```
$ ./wikizimmer.js https://killsixbilliondemons.fandom.com/wiki/KSBD_2:23
module.js:550
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pizzaiolo/Downloads/zimmer-master/wikizimmer.js:41:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

```

**Comment by vss-devel** [comment]
I can't reproduce it.

Have you installed the dependencies with `npm install`?

**Comment by nicolasmaia** [comment]
I think I installed them globally, not with npm. But that's okay, I found another way.
