### ISSUE TITLE
wikizimmer and self signed certificate

### ISSUE THREAD

**Issue by Aglidic** [vss-devel/zimmer#12]
Hello,

is it a way to handle self signed certificate ?

regards

**Comment by vss-devel** [comment]
I'm afraid I don't understand what it is about. Could you please explain it?

**Comment by Aglidic** [comment]
if a self signed certificate is used on the mediawiki server. Wikizimmer refuse to connect.

Is it possible to have a parameter to "ignore" the self sined certificate or at least uncheck it

**Comment by vss-devel** [comment]
Do you have a server which I could make a test with?

**Comment by Aglidic** [comment]
here is the exact error:
 UserAgent wikizimmer/0.3.0-test (https://github.com/vadp/zimmer email:vadp.devl@gmail.com)
(node:19298) UnhandledPromiseRejectionWarning: RequestError: Error: self signed certificate in certificate chain
    at new RequestError (/opt/zimmer/zimmer/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/zimmer/zimmer/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/zimmer/zimmer/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/zimmer/zimmer/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.onRequestError (/opt/zimmer/zimmer/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
(node:19298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vss-devel** [comment]
Do you have your server on the Internet? What is the URL? 

I need some server for some testing to see if I could do something about it. Otherwise you'd need to fix the issue yourself.

**Comment by Aglidic** [comment]
Hello,
no server it's not on internet for the moment... We are still in testing phase.

**Comment by Aglidic** [comment]
So for the moment to make it work i have to do this:
export NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by vss-devel** [comment]
Well done! I'll make a note of it.
