### ISSUE TITLE
npm install failes because "This Node instance cannot run this module"

### ISSUE THREAD

**Issue by Opalinus** [vss-devel/zimmer#19]
I'm on Ubuntu 18.04.05 and tried manually installing via npm install but ran into an error.

I'd love to get some help as I don't understand enough if there is a fix in zimmer is necessary. All I wanted was to dump a small wiki and make in into a ZIM file

What I did:
```
$ git clone https://github.com/vss-devel/zimmer.git && cd zimmer/
$ npm install
npm WARN prefer global node-gyp@3.8.0 should be installed with -g

> sqlite3@5.0.0 install /tmp/zimmer/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: The N-API version of this Node instance is 1. This module supports N-API version(s) 3. This Node instance cannot run this module.
node-pre-gyp ERR! stack     at Object.module.exports.validate_package_json (/tmp/zimmer/node_modules/node-pre-gyp/lib/util/napi.js:84:9)
node-pre-gyp ERR! stack     at validate_config (/tmp/zimmer/node_modules/node-pre-gyp/lib/util/versioning.js:229:10)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/tmp/zimmer/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at install (/tmp/zimmer/node_modules/node-pre-gyp/lib/install.js:206:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/tmp/zimmer/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/tmp/zimmer/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/tmp/zimmer/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:652:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:663:10)
node-pre-gyp ERR! stack     at Module.load (module.js:565:32)
node-pre-gyp ERR! System Linux 4.15.0-124-generic
node-pre-gyp ERR! command "/usr/bin/node" "/tmp/zimmer/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/zimmer/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
The N-API version of this Node instance is 1. This module supports N-API version(s) 3. This Node instance cannot run this module.
npm ERR! Linux 4.15.0-124-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/zimmer/npm-debug.log

```

[npm-debug.log](https://github.com/vss-devel/zimmer/files/5647746/npm-debug.log)

**Comment by vss-devel** [comment]
Could you please try it with node version >= 10.4.0 as per README?

**Comment by Opalinus** [comment]
Updating nodejs to 10.23.0-1 fixed the error. Thanks for the fast response :)
