### ISSUE TITLE
[ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8

### ISSUE THREAD

**Issue by oswinfox** [vss-devel/zimmer#5]
Hello, 
I try to make a zim file from a wiki and I get this error when typping: `./zimmer.js wiki_folder`: 

```text
Unhandled rejection RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:54:9)
    at Buffer.writeUIntLE (internal/buffer.js:484:3)
    at /home/vagrant/zimmer/zimmer.js:1250:17
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/vagrant/zimmer/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/vagrant/zimmer/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/vagrant/zimmer/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/vagrant/zimmer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vagrant/zimmer/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/vagrant/zimmer/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/vagrant/zimmer/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/vagrant/zimmer/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/zimmer/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
```
Any idea what happens? Thanks in advance.

**Comment by vss-devel** [comment]
Which version of node are you using?

**Comment by vss-devel** [comment]
commit 08db346667bb1d57af388bd10dc8b28446c53308 should fix the issue.
